### ISSUE TITLE
Update package on bower to version with concatenating support

### ISSUE THREAD

**Issue by IShm** [dalelotts/angular-date-time-input#23] opened 2016-12-05 19:09 UTC
Hi,

Could you release new version on bower with the [fix](https://github.com/dalelotts/angular-date-time-input/commit/2d5ca7042e40a59eba0bffddcecc720fbb7c5214#diff-25d902c24283ab8cfbac54dfa101ad31) related to concatenating with other files?

Thanks.

**Comment by dalelotts** [comment] 2016-12-06 03:45
Bower is not supported by this project, but you still use it.

The change that you refer to does not require a new release since there is nothing wrong with the code in this project.  Once there is a fix or feature added to this project it will automatically be released when the code is checked in.

See https://github.com/dalelotts/angular-bootstrap-datetimepicker/issues/353 and https://github.com/dalelotts/angular-bootstrap-datetimepicker/issues/347 for more details on how to fix your build process to minifiy and concatenate without injecting defects.

**Closed by dalelotts** 2016-12-06 03:45 UTC

**Comment by matmar10** [comment] 2016-12-16 03:36
Thanks for making a great useful repository. Seriously. I really appreciate it.

What I don't appreciate (and frankly shocked about) is all this pedantic back and fourth over a single semicolon; it's totally and utterly WASTED energy. Swallow your pride and cut a patch release to help people out. Yikes. Think of all the engineering minutes and hours WASTED by people hunting down what the issue is, coming here, and finding out that the only issue is you're too prideful or have your nose up your own semantic arse to just do what's best for the majority of people. Yikes.

By my count you've already written 293 words defending your reasoning of why the simple little semicolon has not already been rolled out in the latest release. 293 wasted words that could have bene avoided by adding a simple semicolon and adding a new tag. What a sad waste of energy that could have been used for productive purposes.

**Comment by dalelotts** [comment] 2016-12-16 05:16
Well that was convincing.

**Comment by dalelotts** [comment] 2016-12-16 05:22
Why don't you solve the root cause of a problem? There is a defect in the build process. If you don't fix it, it is quite likely to break in the future. I suggest you spend your time fixing defects in your code rather than counting the words I write or blaming me for your defective build process.

**Comment by matmar10** [comment] 2016-12-16 07:01
> There is a defect in the build process
> I suggest you spend your time fixing defects in your code 

Thousands of developers use grunt + usemin which has a default pipeline for concatenation and minification. By your logic it's better for thousands of people to go add custom build configuration just because you can't be bothered to tag a release to include a fix that you've already made. That, sir, is just silly.

I'm blaming you for being too arrogant to just cut a simple tag when you've already fixed the issue. *You already added the semicolon.* If you'd just swallowed your pride and just cut a new tag (literally would take 5 seconds), this issue would disappear forever from popping up on this repository and you would save lots of people the future annoyance of looking into this... and you could go back to building awesome stuff instead of arguing with ornery people like me ;-)

**Comment by dalelotts** [comment] 2016-12-16 19:27
Seek first to understand, arrogant one. How many assumptions are in your comments? 

Sorry, _I'm not responsible_ for people making mistakes in their build toolchain or their choice to use tools that don't correctly concatenate JavaScript files. There is _nothing_ wrong with what I have published. Calling me names and engaging in personal attacks (i.e. calling me a douche bag) is not an effective way to get what you want. 

Again, fix the root cause of the problem so you don't spend your time running around the internet blaming other people for your lack of knowledge. (I'm betting that you're a millennial - welcome to the real world!) 

Don't like it, use another directive.

You have to pay for the privilege to tell me what to - you want me to fix your problem, pay me for my time to do it. 

When I am working for free, providing free tools, on my own time, you don't get to tell me what to do. Don't like it? Tough shit. 

Putting up with people like you takes all of the fun out of open source.
