### ISSUE TITLE
Latest version does not include fix: Add semi-colon at end of IIFE's

### ISSUE THREAD

**Issue by matmar10** [dalelotts/angular-date-time-input#24] opened 2016-12-15 22:57 UTC
### Bug Reports
You MUST have a JSBin recreation, or else your issue will be CLOSED without explanation.

Instructions: https://github.com/dalelotts/angular-bootstrap-datetimepicker/wiki/Reporting-Bugs

* __Overview of the Issue__ - Lack of semicolon at the end of the main file causes issue when concatenated with other JS files from other libraries.
* __Motivation for or Use Case__ - This prevents the library from registering with angular, preventing angular from bootstrapping
* __angular-bootstrap-date-formats Version(s)__ - since at least 1.2.1
* __Browsers and Operating System__ - N/A
* __Link to a live example__ - N/A - will submit PR which fixes
* __Related Issues__ - N/A

**Comment by matmar10** [comment] 2016-12-15 23:06
Looks like this is already fixed with 2d5ca7042e40a59eba0bffddcecc720fbb7c5214 but bower install still grabs an older version without it?

**Comment by matmar10** [comment] 2016-12-15 23:10
`bower install --save angular-date-time-input#master` works ok.

Can you tag a new patch version that includes the fix?

**Comment by dalelotts** [comment] 2016-12-16 00:25
This project uses semantic-relase to automate releases - that change was strictly a style change so it does not trigger a new release. It will be in the next release.

If you are having build issues that will be fixed by this change, please review [#347](https://github.com/dalelotts/angular-bootstrap-datetimepicker/issues/347) for options to make your build process more robust.

**Closed** 2016-12-16 00:25 UTC

**Comment by dalelotts** [comment] 2016-12-16 00:27
Duplicate of #23 - please follow instructions when creating defects!
